owner: 上海正鹄会
email: zhenggushanghai@gmail.com
email_send: zhenggushanghai@163.com
email_pwd: zhengguaut0
email_subject: '[system]zhenggu website info'
stmp_tls: false
stmp_addr: smtp.163.com
stmp_port: 25
title: 弓道・上海正鹄会
index: /index
login_level: 10
levels : 
    -   level : 1
        name : 管理员
    -   level : 10
        name : 会员
    -   level : 1000
        name : 游客
